package com.example.gd_bean_ui.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.gd_bean_ui.vo.MenuInfo;
import com.example.gd_bean_ui.vo.MenuSong;
import com.example.gd_bean_ui.vo.SingerInfo;
import com.example.gd_bean_ui.vo.SongInfo;
import com.example.gd_bean_ui.vo.UserInfo;

import com.example.gd_bean_ui.greendao.MenuInfoDao;
import com.example.gd_bean_ui.greendao.MenuSongDao;
import com.example.gd_bean_ui.greendao.SingerInfoDao;
import com.example.gd_bean_ui.greendao.SongInfoDao;
import com.example.gd_bean_ui.greendao.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig menuInfoDaoConfig;
    private final DaoConfig menuSongDaoConfig;
    private final DaoConfig singerInfoDaoConfig;
    private final DaoConfig songInfoDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final MenuInfoDao menuInfoDao;
    private final MenuSongDao menuSongDao;
    private final SingerInfoDao singerInfoDao;
    private final SongInfoDao songInfoDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        menuInfoDaoConfig = daoConfigMap.get(MenuInfoDao.class).clone();
        menuInfoDaoConfig.initIdentityScope(type);

        menuSongDaoConfig = daoConfigMap.get(MenuSongDao.class).clone();
        menuSongDaoConfig.initIdentityScope(type);

        singerInfoDaoConfig = daoConfigMap.get(SingerInfoDao.class).clone();
        singerInfoDaoConfig.initIdentityScope(type);

        songInfoDaoConfig = daoConfigMap.get(SongInfoDao.class).clone();
        songInfoDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        menuInfoDao = new MenuInfoDao(menuInfoDaoConfig, this);
        menuSongDao = new MenuSongDao(menuSongDaoConfig, this);
        singerInfoDao = new SingerInfoDao(singerInfoDaoConfig, this);
        songInfoDao = new SongInfoDao(songInfoDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(MenuInfo.class, menuInfoDao);
        registerDao(MenuSong.class, menuSongDao);
        registerDao(SingerInfo.class, singerInfoDao);
        registerDao(SongInfo.class, songInfoDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        menuInfoDaoConfig.getIdentityScope().clear();
        menuSongDaoConfig.getIdentityScope().clear();
        singerInfoDaoConfig.getIdentityScope().clear();
        songInfoDaoConfig.getIdentityScope().clear();
        userInfoDaoConfig.getIdentityScope().clear();
    }

    public MenuInfoDao getMenuInfoDao() {
        return menuInfoDao;
    }

    public MenuSongDao getMenuSongDao() {
        return menuSongDao;
    }

    public SingerInfoDao getSingerInfoDao() {
        return singerInfoDao;
    }

    public SongInfoDao getSongInfoDao() {
        return songInfoDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
